In [1]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml("mnist_784")

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\datasets\_openml.py:1002: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
mnist.data.shape, np.unique(mnist.target)

((70000, 784),
 array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype=object))

In [6]:
X = mnist.data
y = mnist.target

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
ss = StandardScaler()
ss.fit(X_train,y_train)
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

rfc_clf = RandomForestClassifier(random_state=42,n_estimators=500)
classifier = rfc_clf.fit(X_train,y_train)
y_pred = classifier.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[1324    0    5    0    1    0    2    1    9    1]
 [   0 1579    6    6    2    0    0    4    2    1]
 [   2    3 1340    4    5    1    9    7    8    1]
 [   1    0   21 1360    1   11    3   15   12    9]
 [   2    0    3    0 1256    0    3    3    2   26]
 [   3    2    1   14    3 1230    7    1   11    1]
 [   4    1    0    0    5    9 1375    0    2    0]
 [   2    5   18    0    6    1    0 1453    2   16]
 [   0    6   11   16    5    7    5    4 1297    6]
 [   6    7    3   13   15    4    1   12    6 1353]]
0.9690714285714286
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1343
           1       0.99      0.99      0.99      1600
           2       0.95      0.97      0.96      1380
           3       0.96      0.95      0.96      1433
           4       0.97      0.97      0.97      1295
           5       0.97      0.97      0.97      1273
           6       0.98      0.98      0.98      1396
           7     