In [3]:
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset,DataLoader
import matplotlib.pyplot as plt

In [5]:
train_data = pd.read_csv(r"C:\Users\luyil\Downloads\train.csv")
test_data = pd.read_csv(r"C:\Users\luyil\Downloads\test.csv")

In [6]:
train_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [7]:
train_data.shape

(891, 12)

In [8]:
test_data.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [9]:
test_data.shape

(418, 11)

In [10]:
train_data = train_data.drop(["PassengerId"],axis=1)
test_data = test_data.drop(["PassengerId"],axis=1)

In [11]:
train_data = train_data.drop(["Name","Ticket"],axis=1)
test_data = test_data.drop(["Name","Ticket"],axis=1)

In [12]:
print(train_data.shape)
print(test_data.shape)

(891, 9)
(418, 8)


In [13]:
train_data.isnull().mean(), test_data.isnull().mean()

(Survived    0.000000
 Pclass      0.000000
 Sex         0.000000
 Age         0.198653
 SibSp       0.000000
 Parch       0.000000
 Fare        0.000000
 Cabin       0.771044
 Embarked    0.002245
 dtype: float64,
 Pclass      0.000000
 Sex         0.000000
 Age         0.205742
 SibSp       0.000000
 Parch       0.000000
 Fare        0.002392
 Cabin       0.782297
 Embarked    0.000000
 dtype: float64)

In [14]:
len(test_data.columns)

8

In [15]:
train_data.Embarked.mode()
train_data.Age.median()

28.0

In [16]:
train_data.Embarked.fillna('S',inplace=True)
train_data.Age.fillna(28,inplace=True)

In [17]:
test_data.Age.median(), test_data.Fare.mean()

(27.0, 35.627188489208635)

In [18]:
test_data.Fare.fillna(36,inplace=True)
test_data.Age.fillna(27,inplace=True)

In [19]:
train_data.isnull().mean(), test_data.isnull().mean()

(Survived    0.000000
 Pclass      0.000000
 Sex         0.000000
 Age         0.000000
 SibSp       0.000000
 Parch       0.000000
 Fare        0.000000
 Cabin       0.771044
 Embarked    0.000000
 dtype: float64,
 Pclass      0.000000
 Sex         0.000000
 Age         0.000000
 SibSp       0.000000
 Parch       0.000000
 Fare        0.000000
 Cabin       0.782297
 Embarked    0.000000
 dtype: float64)

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
cate = ["Sex","Embarked"]
categorical = train_data.filter(cate)
categorical.head()

Sex Embarked
0    male        S
1  female        C
2  female        S
3  female        S
4    male        S

In [22]:
cate_to_num = pd.get_dummies(categorical,drop_first=True)
cate_to_num

Sex_male  Embarked_Q  Embarked_S
0           1           0           1
1           0           0           0
2           0           0           1
3           0           0           1
4           1           0           1
..        ...         ...         ...
886         1           0           1
887         0           0           1
888         0           0           1
889         1           0           0
890         1           1           0

[891 rows x 3 columns]

In [23]:
filtered_data = train_data.drop(cate,axis=1)
filtered_data = pd.concat([filtered_data, cate_to_num],axis=1)
filtered_data.head()

Survived  Pclass   Age  SibSp  Parch     Fare Cabin  Sex_male  Embarked_Q  \
0         0       3  22.0      1      0   7.2500   NaN         1           0   
1         1       1  38.0      1      0  71.2833   C85         0           0   
2         1       3  26.0      0      0   7.9250   NaN         0           0   
3         1       1  35.0      1      0  53.1000  C123         0           0   
4         0       3  35.0      0      0   8.0500   NaN         1           0   

   Embarked_S  
0           1  
1           0  
2           1  
3           1  
4           1

In [24]:
X = filtered_data.drop(["Survived","Cabin"],axis=1)
y = filtered_data.filter(["Survived"])
X.head(),y.head()

(   Pclass   Age  SibSp  Parch     Fare  Sex_male  Embarked_Q  Embarked_S
 0       3  22.0      1      0   7.2500         1           0           1
 1       1  38.0      1      0  71.2833         0           0           0
 2       3  26.0      0      0   7.9250         0           0           1
 3       1  35.0      1      0  53.1000         0           0           1
 4       3  35.0      0      0   8.0500         1           0           1,
    Survived
 0         0
 1         1
 2         1
 3         1
 4         0)

In [25]:
X.dtypes

Pclass          int64
Age           float64
SibSp           int64
Parch           int64
Fare          float64
Sex_male        uint8
Embarked_Q      uint8
Embarked_S      uint8
dtype: object

In [26]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(X)
X_f = ss.transform(X)

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((712, 8), (179, 8), (712, 1), (179, 1))

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

log_clf = LogisticRegression()
classifier = log_clf.fit(X_train,y_train)
y_pred = classifier.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[93 17]
 [22 47]]
0.7821229050279329
              precision    recall  f1-score   support

           0       0.81      0.85      0.83       110
           1       0.73      0.68      0.71        69

    accuracy                           0.78       179
   macro avg       0.77      0.76      0.77       179
weighted avg       0.78      0.78      0.78       179



C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [29]:
from sklearn.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier()
classifier = knn_clf.fit(X_train,y_train)
y_pred = classifier.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[94 16]
 [29 40]]
0.7486033519553073
              precision    recall  f1-score   support

           0       0.76      0.85      0.81       110
           1       0.71      0.58      0.64        69

    accuracy                           0.75       179
   macro avg       0.74      0.72      0.72       179
weighted avg       0.74      0.75      0.74       179



C:\ProgramData\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [30]:
from sklearn.ensemble import RandomForestClassifier

rfc_clf = RandomForestClassifier(random_state=42,n_estimators=500)
classifier = rfc_clf.fit(X_train,y_train)
y_pred = classifier.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


[[98 12]
 [19 50]]
0.8268156424581006
              precision    recall  f1-score   support

           0       0.84      0.89      0.86       110
           1       0.81      0.72      0.76        69

    accuracy                           0.83       179
   macro avg       0.82      0.81      0.81       179
weighted avg       0.83      0.83      0.82       179



## K-Fold-Cross-

In [31]:
from sklearn.model_selection import cross_val_score

cross_val_score(classifier, X, y, cv=5, scoring="accuracy")

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for

array([0.79329609, 0.80337079, 0.84269663, 0.76404494, 0.81460674])